### ISSUE TITLE
MPA Planning Domains shapefile not available

### ISSUE THREAD

**Issue by lidefi87** [ccamlr/data#12]
I need to access the MPA Planning Domains shapefile described here: https://www.ccamlr.org/en/science/mpa-planning-domains. I did go to the CCAMLR GIS portal, where I can see this layer, but when I clicked the “download” button, it directs me to this repository. The problem is that this layer is not available here. How can I access this MPA planning domain layer? 

I initially thought it was similar to the statistical areas, and I could merge some of the subareas, but it is not the same. Some boundaries are different, so it would be great to access the correct layer, instead of attempting to recreate it from what I can see in your website.

**Comment by garydewhurst** [comment]
The MPA Planning Domains shapefiles have been added to the repository and is included in release [v0.5.0](https://github.com/ccamlr/data/releases/tag/v0.5.0)
